In [1]:
import pandas as pd
import numpy as np

#categories = pd.read_csv('./data/northwind/categories1.csv')
#products = pd.read_csv('./data/northwind/products.csv')
suppliers = pd.read_csv('./data/northwind/suppliers.csv',
                        usecols=['SupplierID','CompanyName','Country'])
customers = pd.read_csv('./data/northwind/customers.csv',
                        usecols=['CustomerID','CompanyName','Country'])

In [2]:
len(suppliers)

29

In [3]:
len(customers)

91

In [8]:
df_append = suppliers.append(customers,ignore_index=True)

In [9]:
len(df_append)

120

In [10]:
df_append.head(40)

    SupplierID                             CompanyName      Country CustomerID
0          1.0                          Exotic Liquids           UK        NaN
1          2.0              New Orleans Cajun Delights          USA        NaN
2          3.0               Grandma Kelly's Homestead          USA        NaN
3          4.0                           Tokyo Traders        Japan        NaN
4          5.0      Cooperativa de Quesos 'Las Cabras'        Spain        NaN
5          6.0                                Mayumi's        Japan        NaN
6          7.0                            Pavlova Ltd.    Australia        NaN
7          8.0                 Specialty Biscuits Ltd.           UK        NaN
8          9.0                        PB Knäckebröd AB       Sweden        NaN
9         10.0               Refrescos Americanas LTDA       Brazil        NaN
10        11.0             Heli Süßwaren GmbH & Co. KG      Germany        NaN
11        12.0       Plutzer Lebensmittelgroßmärkte AG      Germany        NaN
12        13.0  Nord-Ost-Fisch Handelsgesellschaft mbH      Germany        NaN
13        14.0                 Formaggi Fortini s.r.l.        Italy        NaN
14        15.0                         Norske Meierier       Norway        NaN
15        16.0                       Bigfoot Breweries          USA        NaN
16        17.0                       Svensk Sjöföda AB       Sweden        NaN
17        18.0              Aux joyeux ecclésiastiques       France        NaN
18        19.0             New England Seafood Cannery          USA        NaN
19        20.0                            Leka Trading    Singapore        NaN
20        21.0                              Lyngbysild      Denmark        NaN
21        22.0                     Zaanse Snoepfabriek  Netherlands        NaN
22        23.0                               Karkki Oy      Finland        NaN
23        24.0                              G'day Mate    Australia        NaN
24        25.0                               Ma Maison       Canada        NaN
25        26.0                    Pasta Buttini s.r.l.        Italy        NaN
26        27.0                      Escargots Nouveaux       France        NaN
27        28.0                            Gai pâturage       France        NaN
28        29.0                        Forêts d'érables       Canada        NaN
29         NaN                     Alfreds Futterkiste      Germany      ALFKI
30         NaN      Ana Trujillo Emparedados y helados       Mexico      ANATR
31         NaN                Antonio Moreno Taquer?­a       Mexico      ANTON
32         NaN                         Around the Horn           UK      AROUT
33         NaN                     Berglunds snabbk?¶p       Sweden      BERGS
34         NaN                 Blauer See Delikatessen      Germany      BLAUS
35         NaN               Blondesddsl p?¨re et fils       France      BLONP
36         NaN              B??lido Comidas preparadas        Spain      BOLID
37         NaN                                Bon app'       France      BONAP
38         NaN                   Bottom-Dollar Markets       Canada      BOTTM
39         NaN                           B's Beverages           UK      BSBEV

In [13]:
suppliers2 = suppliers.copy()
customers2 = customers.copy()

In [14]:
suppliers2.rename({'SupplierID':'CustomerID'}, axis='columns',inplace=True)

In [15]:
suppliers2.append(customers2)

   CustomerID                         CompanyName  Country
0           1                      Exotic Liquids       UK
1           2          New Orleans Cajun Delights      USA
2           3           Grandma Kelly's Homestead      USA
3           4                       Tokyo Traders    Japan
4           5  Cooperativa de Quesos 'Las Cabras'    Spain
..        ...                                 ...      ...
86      WARTH                      Wartian Herkku  Finland
87      WELLI              Wellington Importadora   Brazil
88      WHITC                White Clover Markets      USA
89      WILMK                         Wilman Kala  Finland
90      WOLZA                      Wolski  Zajazd   Poland

[120 rows x 3 columns]

In [19]:
df_concatenated = pd.concat(objs=[suppliers2,customers], ignore_index=True)

In [20]:
len(df_concatenated)

120

In [21]:
df_concatenated.head(40)

   CustomerID                             CompanyName      Country
0           1                          Exotic Liquids           UK
1           2              New Orleans Cajun Delights          USA
2           3               Grandma Kelly's Homestead          USA
3           4                           Tokyo Traders        Japan
4           5      Cooperativa de Quesos 'Las Cabras'        Spain
5           6                                Mayumi's        Japan
6           7                            Pavlova Ltd.    Australia
7           8                 Specialty Biscuits Ltd.           UK
8           9                        PB Knäckebröd AB       Sweden
9          10               Refrescos Americanas LTDA       Brazil
10         11             Heli Süßwaren GmbH & Co. KG      Germany
11         12       Plutzer Lebensmittelgroßmärkte AG      Germany
12         13  Nord-Ost-Fisch Handelsgesellschaft mbH      Germany
13         14                 Formaggi Fortini s.r.l.        Italy
14         15                         Norske Meierier       Norway
15         16                       Bigfoot Breweries          USA
16         17                       Svensk Sjöföda AB       Sweden
17         18              Aux joyeux ecclésiastiques       France
18         19             New England Seafood Cannery          USA
19         20                            Leka Trading    Singapore
20         21                              Lyngbysild      Denmark
21         22                     Zaanse Snoepfabriek  Netherlands
22         23                               Karkki Oy      Finland
23         24                              G'day Mate    Australia
24         25                               Ma Maison       Canada
25         26                    Pasta Buttini s.r.l.        Italy
26         27                      Escargots Nouveaux       France
27         28                            Gai pâturage       France
28         29                        Forêts d'érables       Canada
29      ALFKI                     Alfreds Futterkiste      Germany
30      ANATR      Ana Trujillo Emparedados y helados       Mexico
31      ANTON                Antonio Moreno Taquer?­a       Mexico
32      AROUT                         Around the Horn           UK
33      BERGS                     Berglunds snabbk?¶p       Sweden
34      BLAUS                 Blauer See Delikatessen      Germany
35      BLONP               Blondesddsl p?¨re et fils       France
36      BOLID              B??lido Comidas preparadas        Spain
37      BONAP                                Bon app'       France
38      BOTTM                   Bottom-Dollar Markets       Canada
39      BSBEV                           B's Beverages           UK