In [1]:
import pandas as pd
import numpy as np

incidents = pd.read_csv('./data/Canadian Railway Crossing Incidents.csv')
incidents.head(10)

,Region,EventType,Public automated,Public passive,Private,Farm
0,Newfoundland,Accidents,0,0,0,0
1,Newfoundland,Fatalities,0,0,0,0
2,Newfoundland,Serious injuries,0,0,0,0
3,Nova Scotia,Accidents,1,0,0,0
4,Nova Scotia,Fatalities,0,0,0,0
5,Nova Scotia,Serious injuries,0,0,0,0
6,New Brunswick,Accidents,0,0,0,0
7,New Brunswick,Fatalities,0,0,0,0
8,New Brunswick,Serious injuries,0,0,0,0
9,Quebec,Accidents,4,0,1,0

In [2]:
incidents.set_index(['Region', 'EventType'],inplace=True)
incidents.head()

                               Public automated  Public passive  Private  Farm
Region       EventType
Newfoundland Accidents                        0               0        0     0
             Fatalities                       0               0        0     0
             Serious injuries                 0               0        0     0
Nova Scotia  Accidents                        1               0        0     0
             Fatalities                       0               0        0     0

In [3]:
incidents.index

MultiIndex([(         'Newfoundland',        'Accidents'),
            (         'Newfoundland',       'Fatalities'),
            (         'Newfoundland', 'Serious injuries'),
            (          'Nova Scotia',        'Accidents'),
            (          'Nova Scotia',       'Fatalities'),
            (          'Nova Scotia', 'Serious injuries'),
            (        'New Brunswick',        'Accidents'),
            (        'New Brunswick',       'Fatalities'),
            (        'New Brunswick', 'Serious injuries'),
            (               'Quebec',        'Accidents'),
            (               'Quebec',       'Fatalities'),
            (               'Quebec', 'Serious injuries'),
            (              'Ontario',        'Accidents'),
            (              'Ontario',       'Fatalities'),
            (              'Ontario', 'Serious injuries'),
            (             'Manitoba',        'Accidents'),
            (             'Manitoba',       'Fatalities'),
            (             'Manitoba', 'Serious injuries'),
            (         'Saskatchewan',        'Accidents'),
            (         'Saskatchewan',       'Fatalities'),
            (         'Saskatchewan', 'Serious injuries'),
            (              'Alberta',        'Accidents'),
            (              'Alberta',       'Fatalities'),
            (              'Alberta', 'Serious injuries'),
            (     'British Columbia',        'Accidents'),
            (     'British Columbia',       'Fatalities'),
            (     'British Columbia', 'Serious injuries'),
            ('Northwest Territories',        'Accidents'),
            ('Northwest Territories',       'Fatalities'),
            ('Northwest Territories', 'Serious injuries')],
           names=['Region', 'EventType'])

In [4]:
incidents.index.get_level_values(0)

Index(['Newfoundland', 'Newfoundland', 'Newfoundland', 'Nova Scotia',
       'Nova Scotia', 'Nova Scotia', 'New Brunswick', 'New Brunswick',
       'New Brunswick', 'Quebec', 'Quebec', 'Quebec', 'Ontario', 'Ontario',
       'Ontario', 'Manitoba', 'Manitoba', 'Manitoba', 'Saskatchewan',
       'Saskatchewan', 'Saskatchewan', 'Alberta', 'Alberta', 'Alberta',
       'British Columbia', 'British Columbia', 'British Columbia',
       'Northwest Territories', 'Northwest Territories',
       'Northwest Territories'],
      dtype='object', name='Region')

In [5]:
incidents.index.get_level_values(1)

Index(['Accidents', 'Fatalities', 'Serious injuries', 'Accidents',
       'Fatalities', 'Serious injuries', 'Accidents', 'Fatalities',
       'Serious injuries', 'Accidents', 'Fatalities', 'Serious injuries',
       'Accidents', 'Fatalities', 'Serious injuries', 'Accidents',
       'Fatalities', 'Serious injuries', 'Accidents', 'Fatalities',
       'Serious injuries', 'Accidents', 'Fatalities', 'Serious injuries',
       'Accidents', 'Fatalities', 'Serious injuries', 'Accidents',
       'Fatalities', 'Serious injuries'],
      dtype='object', name='EventType')

In [7]:
incidents.head()

                               Public automated  Public passive  Private  Farm
Region       EventType
Newfoundland Accidents                        0               0        0     0
             Fatalities                       0               0        0     0
             Serious injuries                 0               0        0     0
Nova Scotia  Accidents                        1               0        0     0
             Fatalities                       0               0        0     0

In [8]:
incidents.index.set_names(['Area','Event'], inplace=True)
incidents.head()

                               Public automated  Public passive  Private  Farm
Area         Event
Newfoundland Accidents                        0               0        0     0
             Fatalities                       0               0        0     0
             Serious injuries                 0               0        0     0
Nova Scotia  Accidents                        1               0        0     0
             Fatalities                       0               0        0     0